// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tsogwkcxdwfqpsfwpcqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzb2d3a2N4ZHdmcXBzZndwY3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MzIxNzksImV4cCI6MjA4ODQwODE3OX0.Hn7fJAeRWsguEv-fKgqWJVUCa_EBMmJum4TUYi3Hhk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);