// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lfgkwrkvrwmtltjwlufc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZ2t3cmt2cndtdGx0andsdWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMDA3ODgsImV4cCI6MjA3Nzg3Njc4OH0.CVTgLrvU2BdGZ27b525HzKqksC1Vdh5IZtsg3EmPi8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);